### ISSUE TITLE
Default classes on panel with table should just be `table`

### ISSUE THREAD

**Issue by danielfriis** [kaspernj/bootstrap_builders#27]
`= bb_panel "Title of panel", table: true do`

Should only yield `table` class.

If you want other than the default bootstrap table (http://getbootstrap.com/css/#tables-example) you'd use `bs_classes: [:striped]`.

**Comment by danielfriis** [comment]
Just realized that you can set default classes with:

`BootstrapBuilders.configuration.default_table_classes = [:striped, :hover]`

Perfect solution.

Maybe the configuration should be extended to btn's etc. Like:

`BootstrapBuilders.configuration.btn.new.icon = :plus`

**Comment by kaspernj** [comment]
Default icons configurable in https://github.com/kaspernj/bootstrap_builders/pull/29
