### ISSUE TITLE
Consistent use of btn small and mini

### ISSUE THREAD

**Issue by danielfriis** [kaspernj/bootstrap_builders#4]
Bootstrap allows for `btn-block`, `btn-lg`, `btn-md`, `btn-sm` and `btn-xs`.

Right now, when you set `bb_btn, small: true` you get `btn-xs`, as with `bb_btn, mini: true`. Would be nice if `small` returned `btn-sm` and mini `btn-xs`

**Comment by kaspernj** [comment]
`mini` is supposed to be a shortcut for stripping the label and making the button as small as possible.

Maybe argument like `block`, `lg`, `md`, `sm` and `xs` instead of `small`? Those classes are not very human understandable, but instead maps nicely directly to the Bootstrap framework.

I imagine something like this:
```ruby
bb_btn "/url", "Label", :lg, :block, confirm: true
```

The same in regards to the `mini`-argument. The line would be spammed with `: true` if it was done through the hash arguments.

**Comment by kaspernj** [comment]
@danielfriis I have created a PR for this. Do you mind taking a look?

**Comment by danielfriis** [comment]
I think arguments to `bb_btn` as you describe above makes great sense. 

However, if I were to play the devils advocate, I would say that the arguments might be specific to this version of bootstrap and thus working a bit against the benefits of BootstrapBuilders.

**Comment by kaspernj** [comment]
Has any of the classes changed in the next version? I am not sure I understand what you mean.

**Comment by danielfriis** [comment]
From 2.x to 3.0, `btn-small` became `btn-sm`.

From 3.x to 4.0, there's som changes as well: http://v4-alpha.getbootstrap.com/migration/

**Comment by danielfriis** [comment]
In 4.0 `btn-xs` is dropped entriely e.g.

**Comment by kaspernj** [comment]
I would argue we should target 3 primarily. Lets keep `xs` until 4 goes stable.

Do you agree?

**Comment by danielfriis** [comment]
Hard to say honestly. If you'd like the project to make it easy to maintain view-code across bootstrap version, I think you need classes that are independent of bootstrap. The downside is that it makes it difficult to infer the underlying bootstrap class.

**Comment by kaspernj** [comment]
The project is not meant as a way to maintain a whole project through versions. It is just meant to make it easier to write Bootstrap without repeating yourself so much :-)

**Comment by kaspernj** [comment]
Can you think of a nice way to do it? I would love to simplify it :-)
