### ISSUE TITLE
Remove h3 from bb_tabs

### ISSUE THREAD

**Issue by danielfriis** [kaspernj/bootstrap_builders#43]
Trello: https://trello.com/c/2k3pqxND/98
Task: https://tasks.kaspernj.org/tasks/4184

No reason to include `h3` after the tabs. Can be easily included otherwise.

**Comment by kaspernj** [comment]
@danielfriis Is there a Trello card for this as well? :-)

**Comment by danielfriis** [comment]
Yes: https://trello.com/c/2k3pqxND/98-bbtabs-remove-h3

**Comment by kaspernj** [comment]
@danielfriis Fixed in 0.0.43
